name: Build and Test

on:
  push:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    container:
      image: oraclelinux:9
    steps:
      - name: Install Git (if needed)
        run: |
          dnf install -y git
          git --version
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: 'recursive'

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --release

      - name: Run Tests
        run: cargo test

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu
          path: target/release/ltengine*
