name: Build and Test

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        features:
          - ""
          - "cuda"
          - "vulkan"
          - "metal"
        include:
          - os: macos-latest
            features: "metal"
          - os: windows-latest
            features: "cuda"
          - os: windows-latest
            features: "vulkan"
          - os: ubuntu-latest
            features: "cuda"
          - os: ubuntu-latest
            features: "vulkan"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: |
          if [ "${{ matrix.features }}" != "" ]; then
            cargo build --release --features ${{ matrix.features }}
          else
            cargo build --release
          fi

      - name: Run Tests
        run: |
          if [ "${{ matrix.features }}" != "" ]; then
            cargo test --features ${{ matrix.features }}
          else
            cargo test
          fi

      - name: Upload Artifact
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-${{ matrix.features }}
          path: target/release/ltengine*
